### ISSUE TITLE
Field tabs are broken

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft3-recipe#1]
Craft's support for Tabs other than as a single sub-element of the page was deprecated as of RC 1 as per:

https://github.com/craftcms/cms/issues/2660

This means I'll need to roll my own CSS/JS to fix them in Recipe

**Comment by darylknight** [comment]
+1. Any news on this? Just started using it on a new site and noticed this.

**Comment by khalwat** [comment]
It's on my list; I rewrote things to work for SEOmatic, and will circle back and back-port it here.

**Comment by aladrach** [comment]
+1 as well. Any updates?

**Comment by byTwinn** [comment]
+1, starting to use your plugin :) 
Any news ? Thanks

**Comment by khalwat** [comment]
Fixed in 1.0.8 https://github.com/nystudio107/craft-recipe/releases/tag/1.0.8
