### ISSUE TITLE
Abbreviation of grams

### ISSUE THREAD

**Issue by Chalkin** [nystudio107/craft3-recipe#10]
Hey,

I found that the abbreviation for grams which is used by craft-recipe is "gs" - "g" would be the correct abbreviation.

**Example:**
150 gs should be 150 g

**Comment by Chalkin** [comment]
Same goes for mls -> correct would be ml

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-recipe/commit/2d7d8b18769558bcf9a10509784fbb43939799cf
