### ISSUE TITLE
Retrieve recipes by rating

### ISSUE THREAD

**Issue by rtrudel** [nystudio107/craft3-recipe#11]
Is there a way to retrieve recipes with best/worst ratings?

In worst case, I guess I will have to use the OnSave event in my own module/plugin and fill another field (number or hidden) using the value of getAggregateRating (which is an ugly hack to me) then query on this dummy field, but I prefered to ask before for a cleaner way.

Thank you! Very nice plugin!

**Comment by khalwat** [comment]
The way things are structured, no. It's just stored as a JSON blob of data, so you'd need to read in each recipe before you could reasonably search through them by field.
