### ISSUE TITLE
Feature Request: Nutrition Facts Label

### ISSUE THREAD

**Issue by mortscode** [nystudio107/craft3-recipe#14]
Would love to leverage the Nutrition tab information of the recipe to create a Nutrition Label like the ones over at [Nutrifox](https://nutrifox.com/).

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-recipe/commit/7e29739c9c93eece902c10d533b7bdd6ff5198d8

### Nutritional Facts

For a nutrition facts label, you can use:

```twig
{{ entry.someRecipe.renderNutritionFacts() }}
```

Which will output a responsive embed nutrition facts label like this:

![recipe03](https://user-images.githubusercontent.com/7570798/78419325-ae101580-7612-11ea-97d1-63e142cb7148.png)

The percentages are based on [US Recommended Dietary Allowances](https://en.wikipedia.org/wiki/Reference_Daily_Intake), but you can pass in your own values as well:

```twig
{{ entry.someRecipe.renderNutritionFacts({
    'calories': 2000,
    'carbohydrateContent': 275,
    'cholesterolContent': 300,
    'fatContent': 78,
    'fiberContent': 28,
    'proteinContent': 50,
    'saturatedFatContent': 20,
    'sodiumContent': 2300,
    'sugarContent': 50,
}) }}
```
