### ISSUE TITLE
Abbreviation for Cups incorrect and whole number adding 0 in front of measurements

### ISSUE THREAD

**Issue by john-henry** [nystudio107/craft3-recipe#16]
Typically you would use `cup` or `cups` and not `c`
The number 0 was prefixing measurements less than a whole number so for `.5 c` it was showing `0¼c` where it should really be showing `¼ cup`

I have a PR [here](https://github.com/nystudio107/craft-recipe/pull/17). The only thing is that users may need to reselect the measurement from dropdown in their entries. I didn't account for this in PR

**Comment by khalwat** [comment]
Pulled it in thx!

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-recipe/releases/tag/1.1.3
