### ISSUE TITLE
Importing via FeedMe or otherwise?

### ISSUE THREAD

**Issue by bryantAXS** [nystudio107/craft3-recipe#19]
Hey @khalwat, what would the process look like for importing a bunch of data into a recipe? I don't believe this is supported with FeedMe at this point, but what about a manual import script or something along those lines?

We've got a project with 1000+ recipes we're looking to move over, would obviously love to automate it!

Thanks!

**Comment by khalwat** [comment]
Probably the best way would be to write a custom importer for FeedMe

**Comment by bryantAXS** [comment]
Is there a specific service, method, or general approach you can point me towards for this? I've used FeedMe's eventing system before to do some overrides for importing data, but not sure of the best approach in this case..

Thanks!

**Comment by bencroker** [comment]
This has been added for the next release:
https://github.com/nystudio107/craft-recipe/blob/develop/CHANGELOG.md

**Comment by bencroker** [comment]
Released in 1.2.0.
