### ISSUE TITLE
Translation into german

### ISSUE THREAD

**Issue by MichaelBrauner** [nystudio107/craft3-recipe#23]
I really like this plugin but its not usefull for us, because we need it in german. 
Is there a way that I write the translation files for you? So you can put in into place.

**Comment by bencroker** [comment]
There's an incomplete English translation file at https://github.com/nystudio107/craft-recipe/blob/develop/src/translations/en/recipe.php

You are welcome to add the missing translation text and create a German version in `/src/translations/de/recipe.php`.

**Comment by khalwat** [comment]
@MichaelBrauner any updates on the translation here?

**Comment by khalwat** [comment]
Will re-open if there is continued interest

**Comment by hhentschel** [comment]
Interest continues: i added a folder "de" with the recipe.php file and started to translate.
but i don't see any changes in the backend area.
am i missing something to get it to work?

inside recipe.php for example:
`'Recipe' => 'Rezept',` or
`'tablespoons' => 'Esslöffel',`

**Comment by bencroker** [comment]
You'll need to ensure that the text you want translated has the `t` filter applied to it in the templates, so for example:

```twig
{# Will not be translated #}
<h1>Recipe</h1>

{# Will be translated #}
<h1>{{ 'Recipe'|t }}</h1>
```

**Comment by hhentschel** [comment]
thanks, yes, i am aware of that. 
when i look into the plugin, the fields i would like to translate have the `t` applied.
i am refering to the backend wording like:
`'Enter the name of this recipe' => 'Rezeptnamen eingeben',`

**Comment by bencroker** [comment]
That should do it, just ensure your CP is in German. You may need to have your new translation file added to composer's autoload too.

```shell
composer dump-autoload
```

**Comment by hhentschel** [comment]
Unfortunatly no luck. Switched CP Language back and forth, and added composers autoload, in local and dev environment.
i cleared the cache.

i tried the same with the campaign plugin, just to make sure, nothing else is interfering. 
it's working there.

 something else i could try?

**Comment by bencroker** [comment]
Can you test translating this line, which appears in the settings page?

https://github.com/nystudio107/craft-recipe/blob/741c854e50da3473461a8692220d6a0e42c805c7/src/translations/en/recipe.php#L23

**Comment by hhentschel** [comment]
This is working. Also other text on the setting page is being translated.

**Comment by bencroker** [comment]
Ah, so it looks like many of the translation filter instances are missing the translation category. All instances of `|t` that are specific to the plugin need to be replaced with `|t('recipe')`.

**Comment by hhentschel** [comment]
Ah, did'nt know that. I Looked it up, thats the case. 
Do you want to change this? Otherwise i can do it as well.
(What would be the best process?)
Also i would provide the translation file for german.

**Comment by bencroker** [comment]
Yes, it would be idea if you could change and submit as a PR, along with your translation file.

**Comment by hhentschel** [comment]
Just can not find time to do it right now, but will provide it. Probably somewhere around April.
