### ISSUE TITLE
Add Additional Conversion Options

### ISSUE THREAD

**Issue by jwrudzin** [nystudio107/craft3-recipe#25]
### Is your feature request related to a problem? Please describe.
When `getIngredients()` is set to convert to imperial, and an ingredient is entered in a metric quantity, this can result in some unattractive and unnecessarily specific fractions.

An example - 450 g is converted to 15 87300/100000 oz

### Describe the solution you would like
It would be great if some additional conversion options were added to the `getIngredients()` function. Such as:

- The ability to separately specify if conversion to fractions is desired. Currently, if I don't want metric units converted to imperial then I don't have the option to turn on conversion to fractions.
- The ability to specify the precision used for fractions. Currently it's set to 5, but setting it to 1 in the code turned the fraction above (87300/100000) into 9/10 which of course works better for ingredients. In lieu of adding this as an option, I think defaulting to 1 here would be better in most cases than 5.

### Describe alternatives you have considered
I created a fork of the repo and:
- Removed lines 434 and 436 from `src/models/Recipe.php` so that the plugin always converts to fractions, regardless of whether it's converting to imperial. Would of course be ideal if this could be specified in a parameter passed to `getIngredients()`.
- In `src/models/Recipe.php`, updated the precision on line 512 from 5 to 1. Again, this would of course be better as a parameter passed to `getIngredients()`.
- In `src/models/Recipe.php`, I added a space in front of the `<sup>` tag, to match the output of the other fraction cases - they all put a space between the whole number and the fraction, but the default case does not.

**Comment by bencroker** [comment]
Can you share a link to your fork so we can see your code?

**Comment by bencroker** [comment]
Added your changes for the next release, thanks!
