### ISSUE TITLE
Needs more salt

### ISSUE THREAD

**Issue by extensibleseth** [nystudio107/craft3-recipe#28]
### Describe the bug
recipe-nutrition-facts.twig does not contain sodium content output.

### Versions
- Plugin version: 1.2.0
- Craft version: 3.5.15

Added in recipe-nutrition-facts.twig:171:
```
                {% if value.sodiumContent | length %}
                    <tr class="recipe-plugin-macros">
                        <td colspan="2"><b>Sodium:</b> {{ value.sodiumContent ~ 'mg' }}</td>
                        <td><b>{{ percentage(value.sodiumContent, rda.sodiumContent) }}</b></td>
                    </tr>
                {% endif %}
```

**Comment by bencroker** [comment]
Added in https://github.com/nystudio107/craft-recipe/commit/902e7b9d325d0dadb1f00b0a6597e65a6fd03b2c for the next release, thanks!
