### ISSUE TITLE
Asset Sources setting stores asset volume ID instead of folder ID

### ISSUE THREAD

**Issue by bwlng** [nystudio107/craft3-recipe#3]
I noticed recipe fields weren't saving their *Asset Sources* setting because the modal to select an image was empty on a newly created field.

After some digging, it looks like the native Assets field stores the folder ID and the Recipe field is storing the volume ID. I tried manually editing the setting in the recipe field's settings in the database and was able to select an image in the recipe field.

Example of working setting:

    {"assetSources":["folder:3"]}

Example of settings as currently saved by the recipe field’s settings page:

    {"assetSources":["1"]}

**Comment by aladrach** [comment]
Any updates on this? This fix does not appear to work anymore on Craft 3.1.

**Comment by khalwat** [comment]
Looks like it needs to be updated for 3.1 as per: https://craftcms.com/guides/updating-plugins-for-craft-3-1

**Comment by khalwat** [comment]
Fixed in 1.0.10 -> https://github.com/nystudio107/craft-recipe/releases/tag/1.0.10
