### ISSUE TITLE
Add Recipe Equipment Field

### ISSUE THREAD

**Issue by lucaslink** [nystudio107/craft3-recipe#32]
### Is your feature request related to a problem? Please describe.
Many chefs provide equipment lists along with their ingredient lists and directions.

### Describe the solution you would like
It would be extremely helpful if this plugin added an additional field for Recipe Equipment, which would mimic the Recipes Direction field. 

### Describe alternatives you have considered
Adding fields outside of the Recipe field type is just a lot less tidy for content editors.

### Additional context
What would be even cooler is if there was a settings page for the plugin that allowed you to turn fields/tabs on and off from display.

**Comment by khalwat** [comment]
It's on the docket to be added soon!

It will be implemented using the `tool` sub-property of the Recipe schema.org type -> https://schema.org/tool

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-recipe/commit/9ed870eeae654831c8dfcea86c01f3f7d452277b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.3.1",
```
Then do a `composer clear-cache && composer update`
