### ISSUE TITLE
Can't generate Nutritional Analysis information

### ISSUE THREAD

**Issue by OneMohrTime** [nystudio107/craft3-recipe#34]
### Describe the bug
`Error fetching nutritional information from API.`
(I was looking at a programmatic solution to retrieving exactly this info also, so thank you!)

### To reproduce
- Update **Recipe** to `1.3.0` for access to the Edamam API
- Sign up for Nutritional Analysis developer account, generate ID & Key
- Add key & ID to plugin settings
- Run `./craft recipe/nutrition-api/generate --section=recipes --field=recipe` (failed for me)
- Navigate to entry in CP, navigate to Nutrition tab, click "Fetch Info" (failed for me)

### Expected behaviour
Receive nutritional analysis of recipes on [https://recipes.onemohrti.me/recipes](https://recipes.onemohrti.me/recipes)

### Screenshots
![Screen Shot 2021-03-16 at 10 22 16](https://user-images.githubusercontent.com/11075805/111325919-84dd6f00-8642-11eb-9b0a-03bb224e468a.png)
![Screen Shot 2021-03-16 at 10 31 11](https://user-images.githubusercontent.com/11075805/111326202-bce4b200-8642-11eb-8f59-0711a91e094d.png)
(the executable on the server is actually located at (`./craft/operations/`)

### Logs
```bash
2021-03-15 22:07:56 - error - yii\console\UnknownCommandException
yii\base\InvalidRouteException: Unable to resolve the request "recipe/nutrition-api/generate". in /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('recipe/nutritio...', Array)
#1 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('recipe/nutritio...', Array)
#2 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('recipe/nutritio...', Array)
#3 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/operations/craft(23): yii\base\Application->run()
#5 {main}

Next yii\console\UnknownCommandException: Unknown command "recipe/nutrition-api/generate". in /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/console/Application.php:183
Stack trace:
#0 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('recipe/nutritio...', Array)
#1 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('recipe/nutritio...', Array)
#2 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#3 /srv/users/onemohrtime/apps/recipes-prod/releases/be02343c268f0e72f71d75fa274115e0d68b6399/operations/craft(23): yii\base\Application->run()
#4 {main}
```

### Versions
- Plugin version: 1.3.0
- Craft version: 3.5.15.1

**Comment by khalwat** [comment]
Try running the commend from the actual directory? e.g.:

```
cd operations/
./craft recipe/nutrition-api/generate --section=recipes --field=recipe
```

If you're getting an invalid route from Yii2, this sounds like a server/environment related issue to me. That console command does exist, and the route looks correct.

**Comment by OneMohrTime** [comment]
Running from the actual directory gave me the same result, unfortunately. I double checked on the section/field handles too, just to make sure.

I'll do some deeper troubleshooting tonight. Would having the executable back on the root level have any effect? From what I can tell, as long as the paths are updated, it should be executable from anywhere (but you're the expert).

```bash
onemohrtime@craft:~$ cd apps/recipes-prod/current/operations/
onemohrtime@craft:~/apps/recipes-prod/current/operations$ ./craft recipe/nutrition-api/generate --section=recipes --field=recipe
Generating nutritional information for 2 entries...
[==============================================] 100% (2/2) ETA: n/a
Successfully generated nutritional information for 0 entries.
Failed to generate nutritional information for 2 entries.
```

![Screen Shot 2021-03-16 at 11 52 13](https://user-images.githubusercontent.com/11075805/111340367-ec99b700-864e-11eb-9bf7-16f5878da3ba.png)

**Comment by bencroker** [comment]
The command is working fine, it looks like the API is unable to determine the nutritional information from the ingredients. Can you test a simple recipe with just some basic ingredients?

**Comment by OneMohrTime** [comment]
Sorry for the delay on this – I just ran the test on a _very_ simple entry (apple and cheese), and the nutritional information did generate with the "Fetch Nutritional Information" button in the CP 👍 

So I guess this issue was made in error – the problem seems to be Edamam's interpretation of my ingredient lists. Thanks!

**Comment by bencroker** [comment]
Mmmm, apple and cheese.
