### ISSUE TITLE
Adjust "Recipe Serves" field type so that it supports non-numeric values

### ISSUE THREAD

**Issue by ryanfoote** [nystudio107/craft3-recipe#36]
### Is your feature request related to a problem? Please describe.
Some recipes produce a variable number of servings. 8-10, for example. In the plugin, the "Recipe Serves" field only accepts numbers.

### Describe the solution you would like
Change the "Recipe Serves" field so that it can accept a wider range of serving values. Finite numbers (4 servings) and a range of servings (8-10 servings).

**Comment by davidwebca** [comment]
I have the exact same requirement. The schema structured data can be used to display a different "unit" of serving (ex.: "3 slices" when talking about a pizza, etc.) Right now, the "serves" field seems to be used to calculate a lot of things in the nutrition api, so keeping it a pure number seems ideal, but adding a separate field for display and schema purposes would be good.

**Comment by khalwat** [comment]
The way I've decided to solve this is by adding a `.createRecipeMetaJsonLd()` method to the Recipe field, which creates an SEOmatic MetaJsonLd item that you can manipulate to your heart's content.

Addressed in: https://github.com/nystudio107/craft-recipe/commit/ba8d86dc561130299a53686b2bc9d353d299022f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 1.4.0",
```
Then do a `composer clear-cache && composer update`
