### ISSUE TITLE
No check for If ingredient is added or not

### ISSUE THREAD

**Issue by johnwbaxter** [nystudio107/craft3-recipe#4]
Hey Andrew,

Looks like there is no check to see if there is an ingredient existing before trying to loop through those ingredients. It's causing quite a few pages to fall over here!!

2018-10-15 12:19:52 [-][1][85617dc1b198187482659df32038b6d7][error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /xx/vendor/nystudio107/craft-recipe/src/models/Recipe.php:294

Thanks :)

John

**Comment by johnwbaxter** [comment]
Same thing with the instructions, it bails if you don't have at least one.

Ta

**Comment by aladrach** [comment]
Submitted a PR for this issue: https://github.com/nystudio107/craft-recipe/pull/6

**Comment by khalwat** [comment]
Fixed in 1.0.9 ; thanks @aladrach https://github.com/nystudio107/craft-recipe/releases/tag/1.0.9
