### ISSUE TITLE
Support for 1/3, 1/6, etc fractions

### ISSUE THREAD

**Issue by aladrach** [nystudio107/craft3-recipe#5]
Would love to see the fractions update from the 2.x version!

**Comment by aladrach** [comment]
Submitted a PR for this issue: https://github.com/nystudio107/craft-recipe/pull/6

**Comment by khalwat** [comment]
Fixed in 1.0.9 ; thanks @aladrach https://github.com/nystudio107/craft-recipe/releases/tag/1.0.9
