### ISSUE TITLE
Print recipe ingredients in format useful for import

### ISSUE THREAD

**Issue by aaronlax** [nystudio107/craft3-recipe#51]
I am trying to move recipes between craft installation using the feedme plugin, and while the import appears to allow for ingredient by row (quantity, unit, ingredient) the ingredient tag itself does not have the option to output in that format, only the formatted complete output.

How can I access the recipe ingredient table values in their stored format?

**Comment by khalwat** [comment]
I'm not sure tbh -- @engram-design was nice enough to do the FeedMe integration, but I'm not sure how it works.

**Comment by aaronlax** [comment]
This is specific to the recipes plug-in, maybe a feature request. There should be the option to output quantity, unit, and ingredient by row.

**Comment by khalwat** [comment]
Okay I completely misread what you were asking. You weren't asking about importing anything, but rather about being able to access the data from the field individually, yes?

**Comment by khalwat** [comment]
Will re-open if more information is provided
