### ISSUE TITLE
other languages possible?

### ISSUE THREAD

**Issue by hhentschel** [nystudio107/craft3-recipe#52]
The plugin is only in english right now, right?
Is there a way to implement other languages, like german?
or how difficult/much work is it?

I would be happy to provide the translation file, if that would help.

**Comment by khalwat** [comment]
The plugin itself can be translated via: https://github.com/nystudio107/craft-recipe/tree/develop/src/translations

The content stored by the plugin can be in any language, just like any other Craft CMS field.
