### ISSUE TITLE
Nutritional Info is not divided by the number of servings

### ISSUE THREAD

**Issue by keyname** [nystudio107/craft3-recipe#66]
When the Nutritional Info is rendered, the total number of calories and macronutrients are shown, the amounts are not divided by the number of servings.

- Plugin version: dev-develop-v4 as 4.0.6
- Craft version: 4.3.10

**Comment by khalwat** [comment]
Can you add a screenshot that shows what you're seeing, and what you're expecting to see?

**Comment by keyname** [comment]
<img width="635" alt="Screenshot 2023-02-22 at 1 57 12 PM" src="https://user-images.githubusercontent.com/1231754/220731512-f77abccc-2107-4ca9-97d8-d0aca754aff8.png">
<img width="631" alt="Screenshot 2023-02-22 at 1 57 32 PM" src="https://user-images.githubusercontent.com/1231754/220731515-cdff48d2-6d6b-479f-9edd-164fe2352fc5.png">

No matter how many servings, the recipe is divided into, the nutritional information does not change.
Nutritional labels should show the calories, etc. for each serving, not the whole recipe.

**Comment by khalwat** [comment]
Thanks for that! Should be easy to fix.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-recipe/commit/fde38764cf675d288a61befbff770dd5b6c099be & https://github.com/nystudio107/craft-recipe/commit/bb7248285a0501987ef28b6dacdd2e3a5ad0eb8d

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.4",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.7",
```
Then do a `composer clear-cache && composer update`

**Comment by keyname** [comment]
Raw numbers have been corrected, but percentages still need to be corrected.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-recipe/commit/a5da044da4b002af1b82f8c57937997cb0e37bab & https://github.com/nystudio107/craft-recipe/commit/818cb1188c7dc0c3ebdcc79b85f5d5b03630921f

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.4",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.7",
```
Then do a `composer clear-cache && composer update`

**Comment by keyname** [comment]
"Serving Size" does not update according to the number of servings.

**Comment by khalwat** [comment]
hmmm... should "serving size" change with "servings" though?

**Comment by keyname** [comment]
Yes. If I make a recipe that has a total weight of 500g, and serves five people.
The Serving Size is 100g, not 500g.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-recipe/commit/d1d5b827f020c727580ab90861f22ca8b70e1c15 & https://github.com/nystudio107/craft-recipe/commit/088b9db98a85880ff43a00de580a3f42f4dcee3d

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.4",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.7",
```
Then do a `composer clear-cache && composer update`

**Comment by keyname** [comment]
I'm getting the following error: Error rendering `recipe-nutrition-facts` -> An exception has been thrown during the rendering of a template ("A non-numeric value encountered").

**Comment by khalwat** [comment]
Probably you have something non-numeric in the `servingSize` field. If you want to do division based on the serving size, it needs to be a number.

**Comment by keyname** [comment]
Screen shot attached showing the value currently in the Nutrition tab Serving Size.

<img width="1004" alt="Screenshot 2023-02-22 at 8 28 35 PM" src="https://user-images.githubusercontent.com/1231754/220801914-c69f9e37-8d5e-4580-90c7-fb869555e790.png">

**Comment by keyname** [comment]
Additional Screenshot showing the ingredients and Recipe Serves field.
<img width="982" alt="Screenshot 2023-02-22 at 8 36 05 PM" src="https://user-images.githubusercontent.com/1231754/220802768-aa5e4601-9f5d-4393-930d-8d0378ef5884.png">

**Comment by khalwat** [comment]
Yes, `258 grams` is a text string, not a number.

**Comment by keyname** [comment]
That's what is entered by the plug-in when I fetch the nutrition info... not entered manually.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-recipe/commit/2f6a74be701f87f85b1899980e8f140c738a0cca & https://github.com/nystudio107/craft-recipe/commit/678739ae52c3beb034b282fd4eda705899b560bc

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.4",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.7",
```
Then do a `composer clear-cache && composer update`

**Comment by keyname** [comment]
Working great now. Thanks! : )

**Comment by khalwat** [comment]
Okay, will cut a release shortly
