### ISSUE TITLE
MultiComponent Recipe Nutritional Information

### ISSUE THREAD

**Issue by keyname** [nystudio107/craft3-recipe#67]
When creating a multi-component recipe...
(https://nystudio107.com/docs/recipe/#multi-component-recipes)

There is no way to pull nutritional information for the final/combined recipe.

There should be a way to pull the combined, nutritional information for all Recipe Fields in the Section.

**Comment by khalwat** [comment]
You're welcome to do that yourself by making your own template to output the information. Have a look at the Twig template that it uses internally:

https://github.com/nystudio107/craft-recipe/blob/develop/src/templates/recipe-nutrition-facts.twig#L111

**Comment by khalwat** [comment]
Docs for outputting this information yourself in a template are here:

https://nystudio107.com/docs/recipe/#using-recipe-in-your-templates
