### ISSUE TITLE
Ratings don't work

### ISSUE THREAD

**Issue by millman2394** [nystudio107/craft3-recipe#7]
Very useful plugin for my Recipe channel.

Just letting you know the "Add a rating" button on the Ratings tab doesn't work.

**Comment by khalwat** [comment]
So it looks like there is some kind of listener, because if you resize the window, the button does work.

Some weird Garnish thing no doubt.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-recipe/commit/0274a5bee5e209b7648f2a167b3d16ff12ccb481
