### ISSUE TITLE
Receiving PHP error on map fields page for products in Feedme

### ISSUE THREAD

**Issue by john-henry** [nystudio107/craft3-recipe#70]
### Describe the bug
Receiving PHP error on map fields page for products in Feedme

`PHP Fatal error:  Declaration of nystudio107\recipe\integrations\RecipeFeedMeField::getMappingTemplate() must be compatible with craft\feedme\base\FieldInterface::getMappingTemplate(): string in /home/site/craft/vendor/nystudio107/craft-recipe/src/integrations/RecipeFeedMeField.php on line 38`

I don't need to map any recipe fields. Only a stock control feed

### Versions
- Plugin version: 4.0.7
- Craft version: 4.5.14
- Feedme Version: 5.3.0

**Comment by john-henry** [comment]
@khalwat Any additional info you need let me know

**Comment by john-henry** [comment]
I've installed dev-develop-v4 and it looks to have fixed the issue

**Comment by khalwat** [comment]
Ah good reminder that I need to cut a release tho, so I'll re-open this issue

**Comment by khalwat** [comment]
4.0.8 released -> https://github.com/nystudio107/craft-recipe/releases/tag/4.0.8
