### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by davydepauw** [nystudio107/craft3-recipe#73]
### Question
I was wondering if Craft 5 support is coming in the near future :)
Thanks! 🙏

**Comment by khalwat** [comment]
Yep, it's on the list!

**Comment by davydepauw** [comment]
Great, thank you!

**Comment by john-henry** [comment]
Happy to test any betas!

**Comment by wmdhosting** [comment]
me too :)

**Comment by jamie-jenks** [comment]
I'm also happy to be a beta tester!

**Comment by johnwbaxter** [comment]
Oooh, didn't realise this wasn't ready! I would also love to test this!!

**Comment by john-henry** [comment]
@johnwbaxter I just ended up recreating with entry type and custom fields and then pushing through what I needed into custom meta in SEOmatic. I did have to recreate all my entry data though

**Comment by johnwbaxter** [comment]
@john-henry Yeah, I thought about doing similar and writing some code to migrate the data over in some fashion! I'm sure Andrew will get round to this though so hopefully I can carry on using this :)

**Comment by khalwat** [comment]
Yep, it's on the list

**Comment by khalwat** [comment]
Likely gonna ship the Craft 5 version tomorrow

**Comment by khalwat** [comment]
Released for Craft 5 -> https://github.com/nystudio107/craft-recipe/releases/tag/5.0.0
