### ISSUE TITLE
UK localisation...

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft3-recipe#9]
I'm using this for a client, and now they've filled out tons of recipes they've raised the issue that the output is not what you expect in Britain:

British recipes use mixed units; metric and imperial (e.g., we use gram and teaspoon and ml - all at once). Ingredient lists do not look right when output as only one unit type. No one here would use 9.9mls (2 teaspoons) in a listing, but would at the same time use 1.5Kg beef and 2 teaspoons Thyme.
Is there a way to output the unit type per ingredient as input, rather than forcing a conversion?

We do not use "gs" to mean Gram. We use g. 400g. Never 400 gs. At the moment I'm planning to use a replace to get " gs" to "g" and " mls" to "ml".

Here's an example of how this is done in the UK: https://www.bbc.co.uk/food/recipes/nigel_slaters_lancashire_48954

**Comment by MattWilcox** [comment]
As it turns out, the way the plugin is already built, you are able to pass any value other than `null`, `imperial`, or `metric` and Unit Conversion will be skipped, spitting out the units as originally entered. So... this works if you want British style unit display, without any tweaks to the plugin:

`{% set ingredients = entry.recipe.getIngredients('original') %}`
`{% for ingredient in ingredients %}`
`	{{ ingredient | replace({" gs": "g", " ml": "ml" }) }}`
`{% endfor %}`

**Comment by khalwat** [comment]
Just like I planned it :)
